# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gr', '\u4e2a\u4eba\u8bb2\u5e08'), ('gx', '\u9ad8\u7b49\u9662\u6821')], default='pxjg', max_length=10, verbose_name='\u7c7b\u522b'),
        ),
    ]
