# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170329_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, verbose_name='\u5e74\u9f84'),
        ),
    ]
