# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170329_2124'),
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u7a0b', 'verbose_name_plural': '\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '\u8bfe\u7a0b\u7ae0\u8282', 'verbose_name_plural': '\u8bfe\u7a0b\u7ae0\u8282'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u8bfe\u7a0b\u89c6\u9891', 'verbose_name_plural': '\u8bfe\u7a0b\u89c6\u9891'},
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u4efb\u8bfe\u6559\u5e08'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
