# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170331_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notes',
            field=models.TextField(default='', verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='tips_needs',
            field=models.TextField(default='', verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60\u80fd\u5b66\u5230\u4ec0\u4e48'),
        ),
    ]
