# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(blank=True, default='\u8fd9\u5bb6\u4f19\u5f88\u61d2,\u4ec0\u4e48\u90fd\u6ca1\u7559\u4e0b', max_length=100, null=True),
        ),
    ]
