# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170327_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%M/%D', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
