# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170328_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('course_orgcourse_orgcourse_orgcourse_orgcourse_orgcourse_orgcourse_orgcourse_orgcourse_orgcourse_org', '\u627e\u56de\u5bc6\u7801')], max_length=10, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', '\u7537'), ('FEMALE', '\u5973')], default='MAN', max_length=6, verbose_name='\u6027\u522b'),
        ),
    ]
